[package]
name = "irc"
version = "0.13.6"
description = "the irc crate – usable, async IRC for Rust "
authors = ["Aaron Weiss <awe@pdgn.co>"]
license = "MPL-2.0"
keywords = ["irc", "client", "thread-safe", "async", "tokio"]
categories = ["asynchronous", "network-programming"]
documentation = "https://docs.rs/irc/"
repository = "https://github.com/aatxe/irc"
readme = "README.md"

[badges]
travis-ci = { repository = "aatxe/irc" }
is-it-maintained-issue-resolution = { repository = "aatxe/irc" }
is-it-maintained-open-issues = { repository = "aatxe/irc" }

[features]
default = ["client", "ctcp", "toml"]
client = ["tokio-codec", "tokio-core", "tokio-io",
    "tokio-mockstream", "tokio-timer", "tokio-tls",
    "futures", "native-tls"]
ctcp = []
nochanlists = []
json = ["serde_json"]
yaml = ["serde_yaml"]

[dependencies]
bufstream = "0.1"
bytes = "0.4"
chrono = "0.4"
encoding = "0.2"
failure = "0.1"
futures = { version = "0.1", optional = true }
log = "0.4"
native-tls = { version = "0.2", optional = true }
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", optional = true }
serde_yaml = { version = "0.7", optional = true }
tokio-codec = { version = "0.1", optional = true }
tokio-core = { version = "0.1", optional = true }
tokio-io = { version = "0.1", optional = true }
tokio-mockstream = { version = "1.1", optional = true }
tokio-timer = { version = "0.1", optional = true }
tokio-tls = { version = "0.2", optional = true }
toml = { version = "0.4", optional = true }

[dev-dependencies]
args = "2.0"
getopts = "0.2"
